#!/bin/bash
GREEN='\033[0;32m'
RED='\033[0;31m'
NO_COLOR='\033[0m'
npx mocha-headless-chrome -f tests.html > tests.log
export TEST_EXIT=$?
if [[ $TEST_EXIT -ne 0 ]]; then
  echo 'exit code' $TEST_EXIT
  echo -e "${RED}Failing tests${NO_COLOR}, tailed log below (see ${RED}tests.log${NO_COLOR} for full output)"
  echo
  echo --
  echo
  tail -20 tests.log
  exit $TEST_EXIT
fi

echo -e "${GREEN}Tests passed OK${NO_COLOR}"